
DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  title VARCHAR(250) NOT NULL,
  bunit VARCHAR(25) NOT NULL,
  place VARCHAR(100) NULL,
  superid INT,
  competencies VARCHAR(250) NOT NULL,
  salary INT
);